ReactorDatabaseWebApp/ReactorDatabaseWebApp/Controllers/ReactorController.cs
using ReactorDatabaseWebApp.CustomCode;
using ReactorDatabaseWebApp.Models;
using ReactorDB_BLL;
using ReactorDB_BLL.Models;
using ReactorDB_DAL;
using ReactorDB_DAL.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Reflection;
using System.Web.Mvc;

namespace ReactorDatabaseWebApp.Controllers
{
    public class ReactorController : Controller
    {
        public ReactorController()
        {
            string connection = ConfigurationManager.ConnectionStrings["dataSource"].ConnectionString;
            string logPathDAL = ConfigurationManager.AppSettings["LogPathDAL"];
            string logPathMVC = ConfigurationManager.AppSettings["LogPathMVC"];
            string logPathBLL = ConfigurationManager.AppSettings["LogPathBLL"];
            _reactorDAO = new ReactorDAO(connection, logPathDAL);
            _moderatorDAO = new ModeratorDAO(connection, logPathDAL);
            _bookmarkDAO = new BookmarkDAO(connection, logPathDAL);
            _reactorBLO = new ReactorBLO(logPathBLL);
            _logger = new LoggerMVC(logPathMVC, connection);
        }
        private ReactorDAO _reactorDAO;
        private ModeratorDAO _moderatorDAO;
        private BookmarkDAO _bookmarkDAO;
        private ReactorBLO _reactorBLO;
        private LoggerMVC _logger;

        // GET: Reactor
        public ActionResult Index()
        {
            List<ReactorPO> reactorPOList = new List<ReactorPO>();
            try
            {
                List<ReactorDO> reactorDOList = _reactorDAO.ObtainAllReactors();
                foreach (ReactorDO reactorDO in reactorDOList)
                {
                    ReactorPO reactorPO = Mapping.Mapper.ReactorDOtoPO(reactorDO);
                    if (reactorPO.ModeratorID != 0)
                    {
                        reactorPO.ModeratorName = _reactorDAO.ObtainModeratorNameByID(reactorPO.ModeratorID);
                    }
                    reactorPOList.Add(reactorPO);
                }
                if (Session["ID"] != null)
                {
                    List<BookmarkDO> bookmarkDOList = _bookmarkDAO.ObtainBookmarksByUserID(int.Parse(Session["ID"].ToString()));
                    if (bookmarkDOList.Count > 0)
                    {
                        List<int> bookmarkReactorIDs = new List<int>();
                        foreach (BookmarkDO bookmarkDO in bookmarkDOList)
                        {
                            bookmarkReactorIDs.Add(bookmarkDO.ReactorID);
                        }
                        ViewBag.Bookmarks = bookmarkReactorIDs;
                    }
                    else
                    {
                        List<int> emptyList = new List<int>();
                        ViewBag.Bookmarks = emptyList;
                    }
                }
                else { }
            }
            catch (Exception ex)
            {
                _logger.LogMessage(ex, "Fatal");
            }
            finally { }
            return View(reactorPOList);
        }

        [HttpGet]
        public ActionResult ReactorDetails(int id)
        {
            ActionResult response = null;
            try
            {
                ReactorDO reactorDO = _reactorDAO.ObtainReactorByID(id);
                if (reactorDO != null)
                {
                    _logger.LogMessage("Info", "Reactor Details", MethodBase.GetCurrentMethod().ToString(),
                                      "User request to view details of reactor with ID #" + id + " is valid.");
                    ReactorPO reactorPO = Mapping.Mapper.ReactorDOtoPO(reactorDO);
                    if (reactorPO.ModeratorID != 0)
                    {
                        reactorPO.ModeratorName = _reactorDAO.ObtainModeratorNameByID(reactorPO.ModeratorID);
                    }
                    else { }

                    if (Session["ID"] != null)
                    {
                        List<BookmarkDO> bookmarkDOList = _bookmarkDAO.ObtainBookmarksByUserID(int.Parse(Session["ID"].ToString()));
                        if (bookmarkDOList.Count > 0)
                        {
                            List<int> bookmarkReactorIDs = new List<int>();
                            foreach (BookmarkDO bookmarkDO in bookmarkDOList)
                            {
                                bookmarkReactorIDs.Add(bookmarkDO.ReactorID);
                            }
                            if (bookmarkReactorIDs.Contains(id))
                            {
                                ViewBag.isBookmarked = true;
                            }
                            else
                            {
                                ViewBag.isBookmarked = false;
                            }
                        }
                        else
                        {
                            ViewBag.isBookmarked = false;
                        }
                    }
                    else { }
                    response = View(reactorPO);
                }
                else
                {
                    _logger.LogMessage("Warning", "Page not found", MethodBase.GetCurrentMethod().ToString(),
                                      "User attempted to navigate to ReactorDetails on null ID " + id + ". " +
                                      "Redirecting to Index.");
                    TempData["idNotFound"] = "The page you were looking for could not be found." +
                                             "You have been returned to the reactor list.";
                    response = RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                _logger.LogMessage(ex, "Fatal");
            }
            finally { }
            return response;
        }

        [SessionCheck("Role", 2, 3)]
        [HttpGet]
        public ActionResult AddReactor()
        {
            try
            {
                _logger.LogMessage("Info", "Add Reactor Get request", MethodBase.GetCurrentMethod().ToString(),
                                    "Request to view Add Reactor form received.");
            }
            catch (Exception ex)
            {
                _logger.LogMessage(ex, "Fatal");
            }
            finally { }

            ReactorPO form = new ReactorPO();
            FillGenerationDropDown(form);
            FillModeratorDropDown(form);

            return View(form);
        }

        [SessionCheck("Role", 2, 3)]
        [HttpPost]
        public ActionResult AddReactor(ReactorPO form)
        {
            ActionResult response = null;
            int rowsAffected;
            try
            {
                _logger.LogMessage("Info", "Add Reactor Post request", MethodBase.GetCurrentMethod().ToString(),
                                "Request to add Reactor information received.");
                if (ModelState.IsValid)
                {
                    _logger.LogMessage("Info", "Model State check passed", MethodBase.GetCurrentMethod().ToString(),
                                        "ReactorPO form model state is valid.");
                    //If thermal and electric power entered, calculate efficiency with BLO
                    if (form.ThermalPower != 0 && form.ElectricPower != 0)
                    {
                        _logger.LogMessage("Attempting to calculate efficiency.");
                        ReactorBO reactorBO = Mapping.Mapper.ReactorPOtoBO(form);
                        form.Efficiency = _reactorBLO.CalculateEfficiency(reactorBO);
                    }
                    else
                    {
                        _logger.LogMessage("Thermal Power or Electric Power not provided. Did not calculate efficiency.");
                    }
                    _logger.LogMessage("Attempting to map Reactor PO to DO.");
                    ReactorDO reactorDO = Mapping.Mapper.ReactorPOtoDO(form);
                    rowsAffected = _reactorDAO.AddNewReactor(reactorDO);

                    if (rowsAffected > 0)
                    {
                        _logger.LogMessage("Info", "New reactor information added", MethodBase.GetCurrentMethod().ToString(),
                                      form.Name + " reactor was added to database.");
                        TempData["addNew"] = "Reactor added successfully.";
                    }
                    else
                    {
                        _logger.LogMessage("Warning", "Add Reactor attempt failed", MethodBase.GetCurrentMethod().ToString(),
                                            "Attempt to add new reactor showed no database rows affected.");
                        TempData["addNew"] = "Failed to add new reactor to database.";
                    }
                    response = RedirectToAction("Index");
                }
                else
                {
                    _logger.LogMessage("Warning", "Model State check failed", MethodBase.GetCurrentMethod().ToString(),
                                        "ReactorPO form model state was not valid. Returning user to View.");
                    FillGenerationDropDown(form);
                    FillModeratorDropDown(form);
                    response = View(form);
                }
            }
            catch (Exception ex)
            {
                _logger.LogMessage(ex, "Fatal");
            }
            finally { }
            return response;
        }

        [SessionCheck("Role", 2, 3)]
        [HttpGet]
        public ActionResult UpdateReactor(int id)
        {
            ReactorPO form = new ReactorPO();
            try
            {
                _logger.LogMessage("Info", "Update Reactor Get request", MethodBase.GetCurrentMethod().ToString(),
                                    "Request for update form for reactor with ID#" + id + " received.");
                ReactorDO reactorDO = _reactorDAO.ObtainReactorByID(id);

ReactorDatabaseWebApp/ReactorDatabaseWebApp/Views/Reactor/AddReactor.cshtml
@using ReactorDatabaseWebApp.Models;
@model ReactorPO
@{
    ViewBag.Title = "AddReactor";
}

<h2>Add New Reactor</h2>

@using (Html.BeginForm("AddReactor", "Reactor", FormMethod.Post))
{
<div class="form-horizontal">
    @Html.LabelFor(model => Model.Name)
    <div class="form-group">
        @Html.TextBoxFor(model => Model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.Name, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.FullName)
    <div class="form-group">
        @Html.TextBoxFor(model => Model.FullName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.FullName, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.IsThermal)
    <div class="form-group">
        <label>Thermal @Html.RadioButtonFor(model => Model.IsThermal, true, new { @class = "form-control" })</label>
        <label>Fast @Html.RadioButtonFor(model => Model.IsThermal, false, new { @class = "form-control" })</label>
    </div>

    @Html.LabelFor(model => Model.ModeratorID)
    <div class="form-group">
        @Html.DropDownListFor(model => Model.ModeratorID, Model.ModeratorDropDown, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.ModeratorID, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.PrimaryCoolant)
    <div class="form-group">
        @Html.TextBoxFor(model => Model.PrimaryCoolant, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.PrimaryCoolant, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.Fuel)
    <div class="form-group">
        @Html.TextBoxFor(model => Model.Fuel, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.Fuel, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.ThermalPower)
    <div class="form-group">
        @Html.TextBoxFor(model => Model.ThermalPower, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.ThermalPower, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.ElectricPower)
    <div class="form-group">
        @Html.TextBoxFor(model => Model.ElectricPower, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.ElectricPower, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.Year)
    <div class="form-group">
        @Html.TextBoxFor(model => Model.Year, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.Year, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.Generation)
    <div class="form-group">
        @Html.DropDownListFor(model => Model.Generation, Model.GenerationDropDown, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.Generation, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.CountryOfOrigin)
    <div class="form-group">
        @Html.TextBoxFor(model => Model.CountryOfOrigin, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.CountryOfOrigin, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.NumberActive)
    <div class="form-group">
        @Html.TextBoxFor(model => Model.NumberActive, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.NumberActive, null, new { @class = "text-danger" })
    </div>

    @Html.LabelFor(model => Model.Notes)
    <div class="form-group">
        @Html.TextAreaFor(model => Model.Notes, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.Notes, null, new { @class = "text-danger" })
    </div>
    <input class="btn btn-success" type="submit" value="Submit" />
</div>
}

ReactorDatabaseWebApp/ReactorDatabaseWebApp/Views/Reactor/Index.cshtml
@using ReactorDatabaseWebApp.Models
@model List<ReactorPO>
@{
    ViewBag.Title = "Index";
}
<head>
    <script src="~/Scripts/site.js"></script>
</head>

<div id="tempData">
@if (TempData.ContainsKey("deletionResult"))
{
    <br />
    <p class="text-info">@TempData["deletionResult"]</p>
}

@if (TempData.ContainsKey("idNotFound"))
{
    <br />
    <p class="text-info">@TempData["idNotFound"]</p>
}

@if (TempData.ContainsKey("addNew"))
{
    <br />
    <p class="text-info">@TempData["addNew"]</p>
}

@if (TempData.ContainsKey("registerFail"))
{
    <br />
    <p class="text-danger">@TempData["registerFail"]</p>
}

@if (TempData.ContainsKey("registerSuccess"))
{
    <br />
    <p class="text-success">@TempData["registerSuccess"]</p>
}

@if (TempData.ContainsKey("loginSuccess"))
{
    <br />
    <p class="text-success">@TempData["loginSuccess"]</p>
}

</div>

<h2>Reactor List</h2>

@if (Model.Count > 0)
{
    <div class="wrapper">
    <table class="table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Moderator</th>
                <th>Fuel</th>
                <th>Spectrum</th>
                <th>Generation</th>
                <th>Operating</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ReactorPO reactorPO in Model)
            {
                <tr>
                    <td>@reactorPO.Name</td>
                    <td>
                        @if (reactorPO.ModeratorName != null)
                        {
                            <div>@reactorPO.ModeratorName</div>
                        }
                        else
                        {
                            <div>--</div>
                        }
                    </td>
                    <td>@reactorPO.Fuel</td>
                    <td>
                        @if (reactorPO.IsThermal)
                        {
                            <div>Thermal</div>
                        }
                        else
                        {
                            <div>Fast</div>
                        }
                    </td>
                    <td>@reactorPO.Generation</td>
                    <td>@reactorPO.NumberActive</td>
                    <td>
                        @Html.ActionLink(" ", "ReactorDetails", new { id = reactorPO.ReactorID }, new { title = "Details", @class = "glyphicon glyphicon-th-list btn btn-default" })
                        @if (Session["Role"] != null)
                        {
                            if (int.TryParse(Session["Role"].ToString(), out int roleID) && roleID >= 2)
                            {
                                @Html.ActionLink(" ", "UpdateReactor", new { id = reactorPO.ReactorID }, new { title = "Edit", @class = "glyphicon glyphicon-pencil btn btn-default" })
                                if (roleID >= 3)
                                {
                                    @Html.ActionLink(" ", "DeleteReactor", new { id = reactorPO.ReactorID }, new
                                    {
                                        title = "Delete",
                                        @class = "glyphicon glyphicon-trash btn btn-default",
                                        @onclick = "return Confirmation('Are you sure you want to permanently delete this reactor?')"
                                    })
                                }
                            }

                            if (ViewBag.Bookmarks != null)
                            {
                                if (ViewBag.Bookmarks.Contains(reactorPO.ReactorID))
                                {
                                    <div id="@("removeBookmark"+reactorPO.ReactorID)" style="display:inline">
                                        @Ajax.ActionLink(" ", "RemoveBookmark", "Bookmark", new { userID = int.Parse(Session["ID"].ToString()), reactorID = reactorPO.ReactorID },
                                                     new AjaxOptions { HttpMethod = "GET", OnSuccess="toggleBookmark("+reactorPO.ReactorID+")" }, new { @class = "glyphicon glyphicon-star btn btn-default" })
                                    </div>
                                    <div id="@("addBookmark"+reactorPO.ReactorID)" style="display:none">
                                        @Ajax.ActionLink(" ", "AddBookmark", "Bookmark", new { userID = int.Parse(Session["ID"].ToString()), reactorID = reactorPO.ReactorID },
                                                     new AjaxOptions { HttpMethod = "GET", OnSuccess = "toggleBookmark(" + reactorPO.ReactorID + ")" }, new { @class = "glyphicon glyphicon-star-empty btn btn-default" })
                                    </div>
                                }
                                else
                                {
                                    <div id="@("addBookmark"+reactorPO.ReactorID)" style="display:inline">
                                        @Ajax.ActionLink(" ", "AddBookmark", "Bookmark", new { userID = int.Parse(Session["ID"].ToString()), reactorID = reactorPO.ReactorID },
                                                     new AjaxOptions { HttpMethod = "GET", OnSuccess = "toggleBookmark(" + reactorPO.ReactorID + ")" }, new { @class = "glyphicon glyphicon-star-empty btn btn-default" })
                                    </div>
                                    <div id="@("removeBookmark"+reactorPO.ReactorID)" style="display:none">
                                        @Ajax.ActionLink(" ", "RemoveBookmark", "Bookmark", new { userID = int.Parse(Session["ID"].ToString()), reactorID = reactorPO.ReactorID },
                                                     new AjaxOptions { HttpMethod = "GET", OnSuccess = "toggleBookmark(" + reactorPO.ReactorID + ")" }, new { @class = "glyphicon glyphicon-star btn btn-default" })
                                    </div>
                                }
                            }
                            else { }

                        }
                    </td>
                </tr>
            }
            @if (Session["Role"] != null && int.TryParse(Session["Role"].ToString(), out int role) && role >= 2)
            {
                <tr><td>@Html.ActionLink("New", "AddReactor", null, new { @class = "btn btn-default" })</td></tr>
            }
        </tbody>
    </table>
    </div>
}
else
{
    <p>No reactor information found.</p>
    if (Session["Role"] != null && int.TryParse(Session["Role"].ToString(), out int role) && role >= 2)
    {
        <p>@Html.ActionLink("Add New Reactor", "AddReactor")</p>
    }
}

ReactorDatabaseWebApp/ReactorDatabaseWebApp/Views/Reactor/ReactorDetails.cshtml
@using ReactorDatabaseWebApp.Models
@model ReactorPO
@{
    ViewBag.Title = "ReactorDetails";
}

@if (Session["Role"] != null)
{
    <div id="sidebar">
        @if (ViewBag.isBookmarked)
        {
            <div id="@("removeBookmark"+Model.ReactorID)" style="display:inline">
                @Ajax.ActionLink(" ", "RemoveBookmark", "Bookmark", new { userID = int.Parse(Session["ID"].ToString()), reactorID = Model.ReactorID },
                                                 new AjaxOptions { HttpMethod = "GET", OnSuccess = "toggleBookmark(" + Model.ReactorID + ")" }, new { @class = "glyphicon glyphicon-star btn btn-default btn-lg" })
            </div>
            <div id="@("addBookmark"+Model.ReactorID)" style="display:none" onclick="toggleBookmark(@Model.ReactorID)">
                @Ajax.ActionLink(" ", "AddBookmark", "Bookmark", new { userID = int.Parse(Session["ID"].ToString()), reactorID = Model.ReactorID },
                                                 new AjaxOptions { HttpMethod = "GET", OnSuccess = "toggleBookmark(" + Model.ReactorID + ")" }, new { @class = "glyphicon glyphicon-star-empty btn btn-default btn-lg" })
            </div>
        }
        else
        {
            <div id="@("removeBookmark"+Model.ReactorID)" style="display:none">
                @Ajax.ActionLink(" ", "RemoveBookmark", "Bookmark", new { userID = int.Parse(Session["ID"].ToString()), reactorID = Model.ReactorID },
                                                 new AjaxOptions { HttpMethod = "GET", OnSuccess = "toggleBookmark(" + Model.ReactorID + ")" }, new { @class = "glyphicon glyphicon-star btn btn-default btn-lg" })
            </div>
            <div id="@("addBookmark"+Model.ReactorID)" style="display:inline">
                @Ajax.ActionLink(" ", "AddBookmark", "Bookmark", new { userID = int.Parse(Session["ID"].ToString()), reactorID = Model.ReactorID },
                                                 new AjaxOptions { HttpMethod = "GET", OnSuccess = "toggleBookmark(" + Model.ReactorID + ")" }, new { @class = "glyphicon glyphicon-star-empty btn btn-default btn-lg" })
            </div>
        }
    </div>
}

<div id="pageWrap">
    @if (Model != null)
    {
        if (TempData.ContainsKey("updateReactor"))
        {
            <br />
            <p class="text-info">@TempData["updateReactor"]</p>
        }

        <h2>@Model.Name  Reactor Details</h2>

        if (Model.FullName != null)
        {
            <h3><i>@Model.FullName</i></h3>
        }

        if (Model.Generation != "")
        {
            <p>Generation @Model.Generation (@Model.Year)</p><br />
        }
        else
        {
            <p>Generation not listed - @Model.Year</p>
        }

        <table id="reactorDetails" class="table-hover">
            <tbody>
                <tr>
                    <td>Neutron Spectrum</td>
                    @if (Model.IsThermal)
                    {
                        <td>Thermal</td>
                    }
                    else
                    {
                        <td>Fast</td>
                    }
                </tr>
                <tr>
                    <td>Moderator</td>
                    <td>@Model.ModeratorName</td>
                </tr>
                <tr>
                    <td>Primary Coolant</td>
                    <td>@Model.PrimaryCoolant</td>
                </tr>
                <tr>
                    <td>Fuel Type</td>
                    <td>@Model.Fuel</td>
                </tr>
                <tr>
                    <td>Thermal Power (MW)</td>
                    @if (Model.ThermalPower != 0)
                    {
                        <td>@Model.ThermalPower</td>
                    }
                    else
                    {
                        <td>--</td>
                    }
                </tr>
                <tr>
                    <td>Electric Power (MW)</td>
                    @if (Model.ElectricPower != 0)
                    {
                        <td>@Model.ElectricPower</td>
                    }
                    else
                    {
                        <td>--</td>
                    }
                </tr>
                <tr>
                    <td>Thermal Efficiency</td>
                    @if (Model.Efficiency != 0)
                    {
                        <td>@Model.Efficiency.ToString("F")%</td>
                    }
                    else
                    {
                        <td>--</td>
                    }
                </tr>
                <tr></tr>
                <tr>
                    <td>Country of Origin</td>
                    <td>@Model.CountryOfOrigin</td>
                </tr>
                <tr>
                    <td>Number Currently Operating</td>
                    <td>@Model.NumberActive</td>
                </tr>
            </tbody>
        </table><br />

        <div class="moreInfo">
            <p><b>Additional Details</b></p>
            <p>@Model.Notes</p>
        </div><br />

        if (Session["Role"] != null)
        {
            <div class="actionBox">
                <h3>Actions</h3>
                @if (int.TryParse(Session["Role"].ToString(), out int role) && role > 1)
                {
                    <span>@Html.ActionLink("Edit", "UpdateReactor", new { id = Model.ReactorID }, new { @class = "btn btn-default" })</span><span> </span>
                    if (role >= 3)
                    {
                        <span>@Html.ActionLink("Delete", "DeleteReactor", new { id = Model.ReactorID }, new { @class = "btn btn-danger", @onclick = "return Confirmation('This reactor will be permanently deleted from the database.')" })</span>
                    }
                }
            </div>
        }
    }
    else
    {
        <p>Reactor information not found.</p>
    }
</div>


<script src="~/Scripts/site.js"></script>

ReactorDatabaseWebApp/ReactorDatabaseWebApp/Views/Reactor/UpdateReactor.cshtml
@using ReactorDatabaseWebApp.Models
@model ReactorPO
@{
    ViewBag.Title = "UpdateReactor";
}

<h2>Update Reactor</h2>

@using (Html.BeginForm("UpdateReactor", "Reactor", FormMethod.Post))
{
    <div class="form-horizontal">
        @Html.HiddenFor(model => Model.ReactorID)

        @Html.LabelFor(model => Model.Name)
        <div class="form-group">
            @Html.TextBoxFor(model => Model.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.Name, null, new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => Model.FullName)
        <div class="form-group">
            @Html.TextBoxFor(model => Model.FullName, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.FullName, null, new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => Model.IsThermal)
        <div class="form-group">
            <label>Thermal @Html.RadioButtonFor(model => Model.IsThermal, true, new { @class = "form-control" })</label>
            <label>Fast @Html.RadioButtonFor(model => Model.IsThermal, false, new { @class = "form-control" })</label>
        </div>

        @Html.LabelFor(model => Model.ModeratorID)
    <div class="form-group">
        @Html.DropDownListFor(model => Model.ModeratorID, Model.ModeratorDropDown, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => Model.ModeratorID, null, new { @class = "text-danger" })
    </div>

        @Html.LabelFor(model => Model.PrimaryCoolant)
        <div class="form-group">
            @Html.TextBoxFor(model => Model.PrimaryCoolant, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.PrimaryCoolant, null, new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => Model.Fuel)
        <div class="form-group">
            @Html.TextBoxFor(model => Model.Fuel, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.Fuel, null, new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => Model.ThermalPower)
        <div class="form-group">
            @Html.TextBoxFor(model => Model.ThermalPower, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.ThermalPower, null, new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => Model.ElectricPower)
        <div class="form-group">
            @Html.TextBoxFor(model => Model.ElectricPower, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.ElectricPower, null, new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => Model.Year)
        <div class="form-group">
            @Html.TextBoxFor(model => Model.Year, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.Year, null, new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => Model.Generation)
        <div class="form-group">
            @Html.DropDownListFor(model => Model.Generation, Model.GenerationDropDown, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.Generation, null, new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => Model.CountryOfOrigin)
        <div class="form-group">
            @Html.TextBoxFor(model => Model.CountryOfOrigin, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.CountryOfOrigin, null, new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => Model.NumberActive)
        <div class="form-group">
            @Html.TextBoxFor(model => Model.NumberActive, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.NumberActive, null, new { @class = "text-danger" })
        </div>

        @Html.LabelFor(model => Model.Notes)
        <div class="form-group">
            @Html.TextAreaFor(model => Model.Notes, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => Model.Notes, null, new { @class = "text-danger" })
        </div>
        <input class="btn btn-success" type="submit" value="Update" />
    </div>
}